# Generated by Django 2.2.5 on 2020-09-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('duedate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
