# Generated by Django 2.2.5 on 2020-09-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200927_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='duedate',
            new_name='due',
        ),
        migrations.RemoveField(
            model_name='task',
            name='enddate',
        ),
    ]
